### ISSUE TITLE
No module 'cindex' (probably a missing dependency)

### ISSUE THREAD

**Issue by khinsen** [dreamtools/dreamtools#60]
Running the example invocation from the README (`dreamtools --challenge d8c1 --sub-challenge sc1a --submission example.zip`) after installation into a fresh Python environment leads to an exception:

```
  File "/Users/hinsen/Temp/dreamtools/lib/python3.4/site-packages/dreamtools/core/__init__.py", line 1, in <module>
    from cindex import concordanceIndex
```

This looks like some dependency has been forgotten in `setup.py`.

**Comment by cokelaer** [comment]
With python3 portage, this should now be fixed.
